[package]
name = "usd-price-token-sale-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.usd-price-token-sale]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
